### ISSUE TITLE
regarding python version

### ISSUE THREAD

**Issue by Prajithp** [bloonix/bloonix-monitoring#1]
may I know the reason why are you rewriting everything to Python? do you guys have any plan to stop perl based version? I have been using it for a while.

**Comment by j-schulz** [comment]
Hi Prajith,

the long answer: https://blog.bloonix.org/bloonix-und-perl-wohin-geht-die-reise-81/

Unfortunately in german, but maybe you can translate it via Google translator.

The short answer: I'm not happy with Perl 6 and believe that Perl 5 has no future. But don't worry, the Python rewrite will be compatible and we will support Perl 5 for the plugin system (check-*).

Regards
Jonny

**Comment by Prajithp** [comment]
Thanks jonny for the clarification. Keep going :+1:
